spring:
  application:
    name: certificate
  datasource:
    username: myappadmin
    password: myappadmin
    url: jdbc:postgresql://localhost:5432/myappdb
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 2400

logging:
  level:
    com.netflix.discovery: ERROR
    org.springframework.cloud.netflix.eureka: ERROR
    root: INFO
    org:
      zalando:
        logbook: TRACE
      springframework:
        web: INFO
    com:
      myapp:
        service: INFO
  file:
    name: logs/certificate-service.log

management.zipkin.tracing.endpoint: "http://zipkin:9411/api/v2/spans"
management.tracing.sampling.probability: 1.0
server.forward-headers-strategy: framework


springdoc:
  swagger-ui.path: /certificate/openapi/swagger-ui.html
  api-docs.path: /certificate/openapi/v3/api-docs
  packagesToScan: com.bozntouran.certificateservice
  pathsToMatch: /**
  cache.disabled: true

  swagger-ui:
    oauth2-redirect-url: /swagger-ui/oauth2-redirect.html
    oauth:
      clientId: writer
      clientSecret: secret-writer
      useBasicAuthenticationWithAccessCodeGrant: true
  oAuthFlow:
    authorizationUrl: https://localhost:8443/oauth2/authorize
    tokenUrl: https://localhost:8443/oauth2/token

api:
  common:
    version: 1.0.0
    title: Certificates service
    description: This API is for reviewing certifications.
    termsOfService: MY TERMS OF SERVICE
    license: MY LICENSE
    licenseUrl: MY LICENSE URL
    externalDocDesc: MY WIKI PAGE
    externalDocUrl: MY WIKI URL
    contact:
      name: Ntouran
      url: URL
      email: ntouran@cert.com

  responseCodes:
    ok:
      description: OK
    badRequest:
      description: Bad Request, invalid format of the request. See response message for more information
    notFound:
      description: Not found, the specified id does not exist
    unprocessableEntity:
      description: Unprocessable entity, input parameters caused the processing to fail. See response message for more information

  certificate:

    get-certificate-byId:
      description: Return a single certificate by id this exists
      notes: |
        # Normal response
        If the requested certificate id is found a certificate will be returned:
        1. Base certificate information

    get-certificate-byParameters:
      description: Returns a page of a specific size based on the parameters given.
      notes: |
        If no paramaeters are give all available cerificates will be returned.

    create-certificate:
      description: Create a new certificate (Admin only)
      notes: |
        Only users with the **Administrator** role can access this endpoint.

    delete-certificate:
      description: Delete a certificate by id (Admin only)
      notes: |
        Only users with the **Administrator** role can delete certificates.

    update-certificate:
      description: Update an existing certificate (Admin only)
      notes: |
        Only users with the **Administrator** role can update certificates.
        

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://${app.auth-server}:9999

resilience4j.timelimiter:
  instances:
    getRealCompanyID:
      timeoutDuration: 2s

management.health.circuitbreakers.enabled: true

resilience4j.circuitbreaker:
  instances:
    getRealCompanyID:
      allowHealthIndicatorToFail: false
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
resilience4j.retry:
  instances:
    getRealCompanyID:
      maxAttempts: 3
      waitDuration: 1000
      retryExceptions:
        - java.lang.RuntimeException
        - org.springframework.web.client.HttpServerErrorException


---
spring.config.activate.on-profile: docker

server.port: 8080

spring:
  datasource:
    username: revMyCertAdmin
    password: revMyCertAdmin
    url: jdbc:postgresql://postgres:5432/review_my_cert_db