-- auto-generated definition
create table certificate
(
    price       double precision not null,
    version     integer          not null,
    company_id  bigint,
    id          bigint generated by default as identity
        primary key,
    update_date timestamp(6),
    description varchar(255),
    field       varchar(255)
        constraint certificate_field_check
            check ((field)::text = ANY
                   ((ARRAY ['IT'::character varying, 'DEVELOPMENT'::character varying, 'PRODUCTION'::character varying, 'CYBERSECURITY'::character varying])::text[])),
    name        varchar(255)     not null,
    public_id   varchar(255)     not null
        unique
);

-- auto-generated definition
create table company
(
    year_of_foundation integer      not null
        constraint company_year_of_foundation_check
            check ((year_of_foundation >= 0) AND (year_of_foundation <= 3000)),
    id                 bigint generated by default as identity
        primary key,
    description        varchar(255),
    version     integer          not null,
    name               varchar(255) not null,
    public_id   varchar(255)     not null
        unique
);

-- auto-generated definition
create table review
(
    stars          smallint                       not null
        constraint review_stars_check
            check ((stars <= 5) AND (stars >= 0)),
    version        integer not null,
    certificate_id bigint                         not null,
    created_date   timestamp(6),
    id             bigint generated by default as identity
        primary key,
    update_date    timestamp(6),
    user_id        bigint                         not null,
    comment        varchar(255),
    public_id   varchar(255)     not null
        unique,
    constraint review_unique_idx
        unique (id, certificate_id, user_id)
);


