spring:
  application:
    name: config-server

server.port: 8888
spring.cloud.config.server.native.searchLocations: file:${PWD}/config-repo

logging:
  level:
    root: INFO
  file:
    name: config-server.log

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
---
spring.config.activate.on-profile: docker
spring.cloud.config.server.native.searchLocations: file:/config-repo